apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual     # Must match PV's storageClassName
