apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"   # Set MySQL root password
            - name: MYSQL_DATABASE
              value: "testdb"         # Database to create on startup
            - name: MYSQL_USER
              value: "testuser"
            - name: MYSQL_PASSWORD
              value: "testpass"
