apiVersion: v1
kind: Namespace
metadata:
  name: dev-team
  labels:
    env: development
    team: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: dev-team          # Deploy this Pod in the dev-team namespace
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
