apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: myapp
type: Opaque
data:
  MYSQL_USER: dGVzdHVzZXI=          # base64 encoded value of "testuser"
  MYSQL_PASSWORD: dGVzdHBhc3M=      # base64 encoded value of "testpass"
  API_KEY: YXBpa2V5MTIzNDU=         # base64 encoded value of "apikey12345"
