apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: myapp
type: Opaque
data:
  MYSQL_USER: dGVzdHVzZXI=          # base64 for "testuser"
  MYSQL_PASSWORD: dGVzdHBhc3M=      # base64 for "testpass"
  API_KEY: YXBpa2V5MTIzNDU=         # base64 for "apikey12345"
  
---

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: app-secret          # Load all Secret keys as env vars
