apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80    

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec: 
  selector:
    app: nginx-app                    # This label must match the Pod label
  ports:
    - protocol: TCP
      port: 80                        # Port exposed by the Service
      targetPort: 80                  # Port inside the container
  type: NodePort                      # Exposes Service on Node IP