apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx-app
spec:
  replicas: 3                       # Number of Pod replicas
  selector:
    matchLabels:
      app: nginx-app                    # Must match Pod template labels
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-app
spec:
  selector:
    app: nginx-app                      # Must match the ReplicaSet Pod labels
  ports:
    - protocol: TCP
      port: 80                      # Port exposed by the Service
      targetPort: 80                # Port inside the Pod
  type: NodePort                    # Options: ClusterIP, NodePort, LoadBalancer
